### ISSUE TITLE
Introduce customize-cra to ease efforts

### ISSUE THREAD

**Issue by ericlo23** [minheq/monorepo-cra-source-map#2]
Hi @vuhminh, I appreciate your works. It saved my day. Nevertheless, due to the newer version of `react-scripts`, the `babel-loader` is no longer at `config.module.rules[2].oneOf[1];`. 

I found that `customize-cra` provides a function `babelInclude` to alter the `include` prop. It implement the logic to find the `babel-loader` so it can be addressed across different versions of `react-scripts`.

I opened a PR, perhaps you may be interested in it.

**Comment by minheq** [comment]
@ericlo23 sorry for checking this issue so late, glad it helped! and thank you for the PR :)
